"""owners_id

Revision ID: c69ce661e32e
Revises: 5faaa61b3dde
Create Date: 2024-01-09 15:59:44.017674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69ce661e32e'
down_revision = '5faaa61b3dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pets_owner_id', 'owners', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pets_owner_id', type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
